-

diff --git a/capture b/capture
--- a/capture
+++ b/capture
@@ -4,7 +4,7 @@
 # Example: ./capture aws sts get-caller-identity
 
 if [ -z "$1" ]; then
-  2> echo "Error: no shell command provided."
+  >&2 echo "Error: no shell command provided."
 fi
 
 echo $( $@ ) > .result
diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -4,7 +4,9 @@
 # Example: extract .UserId
 
 if [ -z "$1" ]; then
-  2> echo "Error: no jq specification provided."
+  >&2 echo "Error: no jq specification provided."
 fi
 
-echo $( cat .result | jq -r $@ )
+RESULT=$( cat .result | jq -r $@ )
+echo $RESULT
+>&2 echo $RESULT
